+ source /root/mugen-riscv/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/mugen-riscv/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the test environment.'
+ message='Start to prepare the test environment.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the test environment.'
Fri Aug 25 03:49:26 2023 - INFO  - Start to prepare the test environment.
+ DNF_INSTALL 'pcp-import-collectl2pcp tar'
+ pkgs='pcp-import-collectl2pcp tar'
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen-riscv/libs/locallibs/rpm_manage.py install --pkgs 'pcp-import-collectl2pcp tar' --node 1 --tempfile ''
+ tmpfile2=/tmp/tmpca3q52z5
+ '[' -z '' ']'
+ tmpfile=/tmp/tmpca3q52z5
+ wget -nd http://jaist.dl.sourceforge.net/sourceforge/collectl/collectl-3.1.3.src.tar.gz
oe_test_pcp_pcp-import-collectl2pcp.sh: line 23: wget: command not found
+ tar zxvf collectl-3.1.3.src.tar.gz
tar (child): collectl-3.1.3.src.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
+ cd collectl-3.1.3
oe_test_pcp_pcp-import-collectl2pcp.sh: line 25: cd: collectl-3.1.3: No such file or directory
+ ./INSTALL
oe_test_pcp_pcp-import-collectl2pcp.sh: line 26: ./INSTALL: No such file or directory
+ cd -
/root/mugen-riscv
+ LOG_INFO 'End to prepare the test environment.'
+ message='End to prepare the test environment.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to prepare the test environment.'
Fri Aug 25 03:49:33 2023 - INFO  - End to prepare the test environment.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Fri Aug 25 03:49:33 2023 - INFO  - Start to run test.
+ SLEEP_WAIT 20
+ wait_time=20
+ cmd=
+ mode=1
+ python3 /root/mugen-riscv/libs/locallibs/sleep_wait.py --time 20 --cmd '' --mode 1
+ collectl -c 5 -f collect
oe_test_pcp_pcp-import-collectl2pcp.sh: line 33: collectl: command not found
++ hostname
++ awk -F . '{print $1}'
+ hostname=10
++ ls
++ grep 10
+ inputfile=
+ test -f
+ CHECK_RESULT 0
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ collectl2pcp -v collectpcp
+ grep 'New instance'
Usage: collectl2pcp inputfile [inputfile ...] archive
Each 'inputfile' is a collectl archive, must be for the same host (may be gzipped).
'archive' is the base name for the PCP archive to be created.

Options:
  -f, --force           forces overwrite of 'archive' if it already exists
  -v, --verbose         enables increasingly verbose messages
  -?, --help            show this usage message and exit
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_pcp_pcp-import-collectl2pcp.sh line 40'
+ message='oe_test_pcp_pcp-import-collectl2pcp.sh line 40'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_pcp_pcp-import-collectl2pcp.sh line 40'
Fri Aug 25 03:49:53 2023 - ERROR - oe_test_pcp_pcp-import-collectl2pcp.sh line 40
+ return 0
+ test -f collectpcp.0 -a -f collectpcp.index -a -f collectpcp.meta
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_pcp_pcp-import-collectl2pcp.sh line 42'
+ message='oe_test_pcp_pcp-import-collectl2pcp.sh line 42'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_pcp_pcp-import-collectl2pcp.sh line 42'
Fri Aug 25 03:49:53 2023 - ERROR - oe_test_pcp_pcp-import-collectl2pcp.sh line 42
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Fri Aug 25 03:49:53 2023 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 2
+ test 2 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Fri Aug 25 03:49:53 2023 - ERROR - failed to execute the case.
+ exit 2
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Fri Aug 25 03:49:53 2023 - INFO  - Start to restore the test environment.
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z /tmp/tmpca3q52z5 ]]
+ '[' 0 -ne 0 ']'
+ '[' 1 == 0 ']'
+ python3 /root/mugen-riscv/libs/locallibs/rpm_manage.py remove --node 1 --pkgs '' --tempfile /tmp/tmpca3q52z5
+ '[' 0 -ne 0 ']'
+ rm -rf './collect*' './wget-log*' '/opt/hp*'
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Fri Aug 25 03:49:54 2023 - INFO  - End to restore the test environment.
