+ source ../common/common_lib.sh
++ source /root/mugen-riscv/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen-riscv/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the test environment.'
+ message='Start to prepare the test environment.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the test environment.'
Fri Aug 18 10:13:59 2023 - INFO  - Start to prepare the test environment.
+ pre_env
+ DNF_INSTALL iperf3
+ pkgs=iperf3
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen-riscv/libs/locallibs/rpm_manage.py install --pkgs iperf3 --node 1 --tempfile ''
+ tmpfile2=/tmp/tmpvbb3als0
+ '[' -z '' ']'
+ tmpfile=/tmp/tmpvbb3als0
+ DNF_INSTALL iperf3 2
+ pkgs=iperf3
+ node=2
+ '[' -z /tmp/tmpvbb3als0 ']'
++ python3 /root/mugen-riscv/libs/locallibs/rpm_manage.py install --pkgs iperf3 --node 2 --tempfile /tmp/tmpvbb3als0
Traceback (most recent call last):
  File "/root/mugen-riscv/libs/locallibs/rpm_manage.py", line 176, in <module>
    exitcode, output = rpm_install(args.pkgs, args.node, args.tempfile)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/mugen-riscv/libs/locallibs/rpm_manage.py", line 66, in rpm_install
    conn = ssh_cmd.pssh_conn(
           ^^^^^^^^^^^^^^^^^^
  File "/root/mugen-riscv/libs/locallibs/ssh_cmd.py", line 53, in pssh_conn
    conn.connect(ip, port, user, password, timeout=timeout)
  File "/usr/lib/python3.11/site-packages/paramiko/client.py", line 377, in connect
    to_try = list(self._families_and_addresses(hostname, port))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/paramiko/client.py", line 202, in _families_and_addresses
    addrinfos = socket.getaddrinfo(
                ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -2] Name or service not known
+ tmpfile2=
+ '[' -z /tmp/tmpvbb3als0 ']'
+ P_SSH_CMD --cmd 'systemctl stop firewalld
             iperf3 -s >/dev/null 2>&1 &
    '
+ python3 /root/mugen-riscv/libs/locallibs/ssh_cmd.py --cmd 'systemctl stop firewalld
             iperf3 -s >/dev/null 2>&1 &
    '
Fri Aug 18 10:14:00 2023 - ERROR - You need to check the environment configuration file to see if this node information exists.
+ LOG_INFO 'End to prepare the test environment.'
+ message='End to prepare the test environment.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to prepare the test environment.'
Fri Aug 18 10:14:00 2023 - INFO  - End to prepare the test environment.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Fri Aug 18 10:14:00 2023 - INFO  - Start to run test.
+ iperf3 -c '' -d
+ grep 'sent.*bytes of.*total'
iperf3: error - unable to connect to server: Name or service not known
+ CHECK_RESULT 1 0 0 'iperf3 -d execution failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='iperf3 -d execution failed.'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'iperf3 -d execution failed.'
+ LOG_ERROR 'iperf3 -d execution failed.'
+ message='iperf3 -d execution failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'iperf3 -d execution failed.'
Fri Aug 18 10:14:00 2023 - ERROR - iperf3 -d execution failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_iperf3_command_clientAndShared.sh line 31'
+ message='oe_test_iperf3_command_clientAndShared.sh line 31'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_iperf3_command_clientAndShared.sh line 31'
Fri Aug 18 10:14:00 2023 - ERROR - oe_test_iperf3_command_clientAndShared.sh line 31
+ return 0
+ iperf3 -c '' -f k
+ grep Kbits
iperf3: error - unable to connect to server: Name or service not known
+ CHECK_RESULT 1 0 0 'iperf3 -f execution failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='iperf3 -f execution failed.'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'iperf3 -f execution failed.'
+ LOG_ERROR 'iperf3 -f execution failed.'
+ message='iperf3 -f execution failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'iperf3 -f execution failed.'
Fri Aug 18 10:14:00 2023 - ERROR - iperf3 -f execution failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_iperf3_command_clientAndShared.sh line 33'
+ message='oe_test_iperf3_command_clientAndShared.sh line 33'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_iperf3_command_clientAndShared.sh line 33'
Fri Aug 18 10:14:00 2023 - ERROR - oe_test_iperf3_command_clientAndShared.sh line 33
+ return 0
+ iperf3 -c '' -V
+ grep Cookie
iperf3: error - unable to connect to server: Name or service not known
+ CHECK_RESULT 1 0 0 'iperf3 -V execution failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='iperf3 -V execution failed.'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'iperf3 -V execution failed.'
+ LOG_ERROR 'iperf3 -V execution failed.'
+ message='iperf3 -V execution failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'iperf3 -V execution failed.'
Fri Aug 18 10:14:00 2023 - ERROR - iperf3 -V execution failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_iperf3_command_clientAndShared.sh line 35'
+ message='oe_test_iperf3_command_clientAndShared.sh line 35'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_iperf3_command_clientAndShared.sh line 35'
Fri Aug 18 10:14:00 2023 - ERROR - oe_test_iperf3_command_clientAndShared.sh line 35
+ return 0
+ iperf3 -c '' -J
+ grep '{'
+ sed -n 1p
{
+ iperf3 -c '' -J
+ sed -n '$p'
+ grep '}'
}
+ CHECK_RESULT 0 0 0 'iperf3 -J execution failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='iperf3 -J execution failed.'
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ iperf3 -c '' --logfile /tmp/iperf3.log
+ CHECK_RESULT 1 0 0 'iperf3 --logfile execution failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='iperf3 --logfile execution failed.'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'iperf3 --logfile execution failed.'
+ LOG_ERROR 'iperf3 --logfile execution failed.'
+ message='iperf3 --logfile execution failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'iperf3 --logfile execution failed.'
Fri Aug 18 10:14:00 2023 - ERROR - iperf3 --logfile execution failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_iperf3_command_clientAndShared.sh line 39'
+ message='oe_test_iperf3_command_clientAndShared.sh line 39'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_iperf3_command_clientAndShared.sh line 39'
Fri Aug 18 10:14:00 2023 - ERROR - oe_test_iperf3_command_clientAndShared.sh line 39
+ return 0
+ iperf3 -c '' -u
+ grep Datagrams
iperf3: error - unable to connect to server: Name or service not known
+ CHECK_RESULT 1 0 0 'iperf3 -u execution failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='iperf3 -u execution failed.'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'iperf3 -u execution failed.'
+ LOG_ERROR 'iperf3 -u execution failed.'
+ message='iperf3 -u execution failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'iperf3 -u execution failed.'
Fri Aug 18 10:14:00 2023 - ERROR - iperf3 -u execution failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_iperf3_command_clientAndShared.sh line 41'
+ message='oe_test_iperf3_command_clientAndShared.sh line 41'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_iperf3_command_clientAndShared.sh line 41'
Fri Aug 18 10:14:00 2023 - ERROR - oe_test_iperf3_command_clientAndShared.sh line 41
+ return 0
+++ sed -n 1p /tmp/tmp
+++ grep real
+++ awk '{print $2}'
++ expr '<' 3
expr: syntax error: unexpected argument ‘3’
+ '[' -eq 1 ']'
oe_test_iperf3_command_clientAndShared.sh: line 43: [: -eq: unary operator expected
+ CHECK_RESULT 2 0 0 'iperf3 -t 2 execution failed.'
+ actual_result=2
+ expect_result=0
+ mode=0
+ error_log='iperf3 -t 2 execution failed.'
+ '[' -z 2 ']'
+ '[' 0 -eq 0 ']'
+ test 2x '!=' 0x
+ test -n 'iperf3 -t 2 execution failed.'
+ LOG_ERROR 'iperf3 -t 2 execution failed.'
+ message='iperf3 -t 2 execution failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'iperf3 -t 2 execution failed.'
Fri Aug 18 10:14:00 2023 - ERROR - iperf3 -t 2 execution failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_iperf3_command_clientAndShared.sh line 44'
+ message='oe_test_iperf3_command_clientAndShared.sh line 44'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_iperf3_command_clientAndShared.sh line 44'
Fri Aug 18 10:14:00 2023 - ERROR - oe_test_iperf3_command_clientAndShared.sh line 44
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Fri Aug 18 10:14:00 2023 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 6
+ test 6 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Fri Aug 18 10:14:00 2023 - ERROR - failed to execute the case.
+ exit 6
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Fri Aug 18 10:14:00 2023 - INFO  - Start to restore the test environment.
+ clean_env
+ P_SSH_CMD --cmd 'kill -9 $(ps -ef | grep \"iperf3 -s\" | grep -v grep | awk '\''{print $2}'\'')
             systemctl start firewalld
             '
+ python3 /root/mugen-riscv/libs/locallibs/ssh_cmd.py --cmd 'kill -9 $(ps -ef | grep \"iperf3 -s\" | grep -v grep | awk '\''{print $2}'\'')
             systemctl start firewalld
             '
Fri Aug 18 10:14:00 2023 - ERROR - You need to check the environment configuration file to see if this node information exists.
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z /tmp/tmpvbb3als0 ]]
+ '[' 0 -ne 0 ']'
+ '[' 1 == 0 ']'
+ python3 /root/mugen-riscv/libs/locallibs/rpm_manage.py remove --node 1 --pkgs '' --tempfile /tmp/tmpvbb3als0
+ '[' 0 -ne 0 ']'
+ rm -rf /tmp/iperf3.log /tmp/tmp
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Fri Aug 18 10:14:01 2023 - INFO  - End to restore the test environment.
