+ source ../common/common_lib.sh
++ source /root/mugen-riscv/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen-riscv/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the test environment.'
+ message='Start to prepare the test environment.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the test environment.'
Fri Aug 18 10:13:56 2023 - INFO  - Start to prepare the test environment.
+ pre_env
+ DNF_INSTALL iperf3
+ pkgs=iperf3
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen-riscv/libs/locallibs/rpm_manage.py install --pkgs iperf3 --node 1 --tempfile ''
+ tmpfile2=/tmp/tmpezz21ik6
+ '[' -z '' ']'
+ tmpfile=/tmp/tmpezz21ik6
+ DNF_INSTALL iperf3 2
+ pkgs=iperf3
+ node=2
+ '[' -z /tmp/tmpezz21ik6 ']'
++ python3 /root/mugen-riscv/libs/locallibs/rpm_manage.py install --pkgs iperf3 --node 2 --tempfile /tmp/tmpezz21ik6
Traceback (most recent call last):
  File "/root/mugen-riscv/libs/locallibs/rpm_manage.py", line 176, in <module>
    exitcode, output = rpm_install(args.pkgs, args.node, args.tempfile)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/mugen-riscv/libs/locallibs/rpm_manage.py", line 66, in rpm_install
    conn = ssh_cmd.pssh_conn(
           ^^^^^^^^^^^^^^^^^^
  File "/root/mugen-riscv/libs/locallibs/ssh_cmd.py", line 53, in pssh_conn
    conn.connect(ip, port, user, password, timeout=timeout)
  File "/usr/lib/python3.11/site-packages/paramiko/client.py", line 377, in connect
    to_try = list(self._families_and_addresses(hostname, port))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/paramiko/client.py", line 202, in _families_and_addresses
    addrinfos = socket.getaddrinfo(
                ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -2] Name or service not known
+ tmpfile2=
+ '[' -z /tmp/tmpezz21ik6 ']'
+ P_SSH_CMD --cmd 'systemctl stop firewalld
             iperf3 -s >/dev/null 2>&1 &
    '
+ python3 /root/mugen-riscv/libs/locallibs/ssh_cmd.py --cmd 'systemctl stop firewalld
             iperf3 -s >/dev/null 2>&1 &
    '
Fri Aug 18 10:13:58 2023 - ERROR - You need to check the environment configuration file to see if this node information exists.
+ LOG_INFO 'End to prepare the test environment.'
+ message='End to prepare the test environment.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to prepare the test environment.'
Fri Aug 18 10:13:58 2023 - INFO  - End to prepare the test environment.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Fri Aug 18 10:13:58 2023 - INFO  - Start to run test.
+ iperf3 -c '' -n 1400 -V
+ grep '1400 bytes to send'
iperf3: error - unable to connect to server: Name or service not known
+ CHECK_RESULT 1 0 0 'iperf3 -n execution failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='iperf3 -n execution failed.'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'iperf3 -n execution failed.'
+ LOG_ERROR 'iperf3 -n execution failed.'
+ message='iperf3 -n execution failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'iperf3 -n execution failed.'
Fri Aug 18 10:13:58 2023 - ERROR - iperf3 -n execution failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_iperf3_command_client.sh line 31'
+ message='oe_test_iperf3_command_client.sh line 31'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_iperf3_command_client.sh line 31'
Fri Aug 18 10:13:58 2023 - ERROR - oe_test_iperf3_command_client.sh line 31
+ return 0
+ iperf3 -c '' -k 1400 -V
+ grep '1400 blocks to send'
iperf3: error - unable to connect to server: Name or service not known
+ CHECK_RESULT 1 0 0 'iperf3 -k execution failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='iperf3 -k execution failed.'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'iperf3 -k execution failed.'
+ LOG_ERROR 'iperf3 -k execution failed.'
+ message='iperf3 -k execution failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'iperf3 -k execution failed.'
Fri Aug 18 10:13:58 2023 - ERROR - iperf3 -k execution failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_iperf3_command_client.sh line 33'
+ message='oe_test_iperf3_command_client.sh line 33'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_iperf3_command_client.sh line 33'
Fri Aug 18 10:13:58 2023 - ERROR - oe_test_iperf3_command_client.sh line 33
+ return 0
+ iperf3 -c '' -P 2
+ grep -c connected
+ grep 2
iperf3: error - unable to connect to server: Name or service not known
+ CHECK_RESULT 1 0 0 'iperf3 -P execution failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='iperf3 -P execution failed.'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'iperf3 -P execution failed.'
+ LOG_ERROR 'iperf3 -P execution failed.'
+ message='iperf3 -P execution failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'iperf3 -P execution failed.'
Fri Aug 18 10:13:58 2023 - ERROR - iperf3 -P execution failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_iperf3_command_client.sh line 35'
+ message='oe_test_iperf3_command_client.sh line 35'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_iperf3_command_client.sh line 35'
Fri Aug 18 10:13:58 2023 - ERROR - oe_test_iperf3_command_client.sh line 35
+ return 0
+ iperf3 -c '' --get-server-output
+ grep 'Server output'
iperf3: error - unable to connect to server: Name or service not known
+ CHECK_RESULT 1 0 0 'iperf3 --get-server-output execution failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='iperf3 --get-server-output execution failed.'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'iperf3 --get-server-output execution failed.'
+ LOG_ERROR 'iperf3 --get-server-output execution failed.'
+ message='iperf3 --get-server-output execution failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'iperf3 --get-server-output execution failed.'
Fri Aug 18 10:13:58 2023 - ERROR - iperf3 --get-server-output execution failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_iperf3_command_client.sh line 37'
+ message='oe_test_iperf3_command_client.sh line 37'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_iperf3_command_client.sh line 37'
Fri Aug 18 10:13:58 2023 - ERROR - oe_test_iperf3_command_client.sh line 37
+ return 0
+++ iperf3 -c '' -w 20240
+++ grep sender
+++ awk '{print $5}'
iperf3: error - unable to connect to server: Name or service not known
+++ iperf3 -c '' -w 102400
+++ grep sender
+++ awk '{print $5}'
iperf3: error - unable to connect to server: Name or service not known
++ expr '>'
+ '[' '>' -eq 0 ']'
oe_test_iperf3_command_client.sh: line 38: [: >: integer expression expected
+ CHECK_RESULT 2 0 0 'iperf3 -w execution failed.'
+ actual_result=2
+ expect_result=0
+ mode=0
+ error_log='iperf3 -w execution failed.'
+ '[' -z 2 ']'
+ '[' 0 -eq 0 ']'
+ test 2x '!=' 0x
+ test -n 'iperf3 -w execution failed.'
+ LOG_ERROR 'iperf3 -w execution failed.'
+ message='iperf3 -w execution failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'iperf3 -w execution failed.'
Fri Aug 18 10:13:58 2023 - ERROR - iperf3 -w execution failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_iperf3_command_client.sh line 39'
+ message='oe_test_iperf3_command_client.sh line 39'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_iperf3_command_client.sh line 39'
Fri Aug 18 10:13:58 2023 - ERROR - oe_test_iperf3_command_client.sh line 39
+ return 0
+ iperf3 -c '' -R
+ grep 'Reverse mode'
iperf3: error - unable to connect to server: Name or service not known
+ CHECK_RESULT 1 0 0 'iperf3 -R execution failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='iperf3 -R execution failed.'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'iperf3 -R execution failed.'
+ LOG_ERROR 'iperf3 -R execution failed.'
+ message='iperf3 -R execution failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'iperf3 -R execution failed.'
Fri Aug 18 10:13:58 2023 - ERROR - iperf3 -R execution failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_iperf3_command_client.sh line 41'
+ message='oe_test_iperf3_command_client.sh line 41'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_iperf3_command_client.sh line 41'
Fri Aug 18 10:13:58 2023 - ERROR - oe_test_iperf3_command_client.sh line 41
+ return 0
+ iperf3 -c '' -T test
+ grep test:
iperf3: error - unable to connect to server: Name or service not known
+ CHECK_RESULT 1 0 0 'iperf3 -T execution failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='iperf3 -T execution failed.'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'iperf3 -T execution failed.'
+ LOG_ERROR 'iperf3 -T execution failed.'
+ message='iperf3 -T execution failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'iperf3 -T execution failed.'
Fri Aug 18 10:13:58 2023 - ERROR - iperf3 -T execution failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_iperf3_command_client.sh line 43'
+ message='oe_test_iperf3_command_client.sh line 43'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_iperf3_command_client.sh line 43'
Fri Aug 18 10:13:58 2023 - ERROR - oe_test_iperf3_command_client.sh line 43
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Fri Aug 18 10:13:58 2023 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 7
+ test 7 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Fri Aug 18 10:13:58 2023 - ERROR - failed to execute the case.
+ exit 7
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Fri Aug 18 10:13:58 2023 - INFO  - Start to restore the test environment.
+ clean_env
+ P_SSH_CMD --cmd 'kill -9 $(ps -ef | grep \"iperf3 -s\" | grep -v grep | awk '\''{print $2}'\'')
             systemctl start firewalld
             '
+ python3 /root/mugen-riscv/libs/locallibs/ssh_cmd.py --cmd 'kill -9 $(ps -ef | grep \"iperf3 -s\" | grep -v grep | awk '\''{print $2}'\'')
             systemctl start firewalld
             '
Fri Aug 18 10:13:58 2023 - ERROR - You need to check the environment configuration file to see if this node information exists.
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z /tmp/tmpezz21ik6 ]]
+ '[' 0 -ne 0 ']'
+ '[' 1 == 0 ']'
+ python3 /root/mugen-riscv/libs/locallibs/rpm_manage.py remove --node 1 --pkgs '' --tempfile /tmp/tmpezz21ik6
+ '[' 0 -ne 0 ']'
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Fri Aug 18 10:13:58 2023 - INFO  - End to restore the test environment.
